In [15]:
import numpy as np


In [16]:
d1 = np.array([1, 3, 4, 6])
print(d1)

[1 3 4 6]


In [17]:
d2 = np.array([[0, 2, 3, 4, 7], 
               [1, 6, 8, 9, 10],
               [23, 44, 67, 89, 100]])
print(d2)

[[  0   2   3   4   7]
 [  1   6   8   9  10]
 [ 23  44  67  89 100]]


In [18]:
d3 = np.array([[[2, 5, 7], [4, 6, 8], [1, 3, 9]]])
print(d3)

[[[2 5 7]
  [4 6 8]
  [1 3 9]]]


In [19]:
d1[0:3:2]


array([1, 4])

In [20]:
d2[1, 2:]

array([ 8,  9, 10])

In [21]:
d2[0:, 0]

array([ 0,  1, 23])

In [22]:
d2[0:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [67, 89]])

In [24]:
dd2 = np.array([[0, 1, 2, 3, 4,5], 
       [6, 7, 8, 9, 10, 11], 
       [12, 13, 14, 15, 16, 17]])

dd2[1:, 3:5]

array([[ 9, 10],
       [15, 16]])