In [2]:
# Numpy

In [3]:
import numpy as np

In [12]:
#Create an 3D array having 3 rows and 4 columns 
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])

In [13]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [14]:
arr.shape

(1, 3, 4)

In [15]:
arr[:, 0:2, 3:5]

array([[[4],
        [8]]])

In [16]:
arr[:, 0::2, 2:]

array([[[ 3,  4],
        [11, 12]]])

#maths function

In [19]:
arr.min()

1

In [20]:
arr.max()

12

In [21]:
arr.mean()

6.5

In [23]:
arr.sum()

78

In [32]:
sum(sum(arr))

array([15, 18, 21, 24])

In [26]:
np.median(arr)

6.5

In [37]:
d2 = np.array([[1,2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 9]])

In [35]:
sum(d2)

array([15, 18, 21, 24])

In [38]:
np.where(d2==9, 50, d2) #it change or reassign the value at a specific without having the element index( but it also change for all dupolicates in array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [50, 10, 11, 50]])

#Reshaping of an array

In [39]:
a1 = np.random.randint(0, 100, 20)

In [40]:
a1.shape

(20,)

In [41]:
a2 = a1.reshape(5,4)

In [42]:
a2

array([[52, 62, 32, 16],
       [44, 99, 92, 87],
       [84, 87, 16, 43],
       [95, 68, 72, 79],
       [18, 86, 91, 56]])

In [43]:
a2.shape

(5, 4)

In [44]:
a2.reshape(4, 5)

array([[52, 62, 32, 16, 44],
       [99, 92, 87, 84, 87],
       [16, 43, 95, 68, 72],
       [79, 18, 86, 91, 56]])

In [46]:
np.linspace(0,100, 15) # Creates a np array of elements in range 0 to 100 with equally distribution of values

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])